# Generated by Django 5.2.13 on 2026-05-12 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0003_alter_measurement_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "ordering": ["-name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="measurements.categorygroup",
                verbose_name="Group",
            ),
            preserve_default=False,
        ),
    ]
